### ISSUE TITLE
Multiple issues for lab 4 coinpurse

### ISSUE THREAD

**Issue by jbrucker** [peachyapc/coinpurse#1]
In code review we found several issues in coin purse.
They are described in the Google sheet shared with you.
Most are small, but there are 3 significant issues:

* comparator does not sort correctly
* sorting is being done inefficiently. Do it only when needed and avoid creating a new Comparator each time.
* only write code that you understand. Change anonymous class to a regular class (inner class in Purse is OK) and create an object from your Comparator class.

Close this issue when all items are fixed.

**Comment by peachyapc** [comment]
already revised.
